server:
  port: 8081

spring:
  application:
    name: springcloud-privade
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    druid:
      initial-size: 5
      maxActive: 20
      maxWait: 60000
      min-idle: 5
      minEvictableIdleTimeMillis: 300000
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/1902a
    username: root
  redis:
    database: 0
    host: 127.0.0.1
    jedis:
      pool:
        max-active: 200
        max-idle: 10
        max-wait: 1
        min-idle: 0
      timeout: 1000
    password:
    port: 6379
mybatis:
  mapper-locations: classpath:mybatis/*.xml
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2


